import AuthProvider from '@/providers/AuthProvider'
import './globals.css'
import { Figtree } from 'next/font/google'
import { LeftBar } from '@/components/leftBar/LeftBar'
import { RightBar } from '@/components/rightBar/RightBar'
import { FooterPlayer } from '@/components/footerPlayer/FooterPlayer'
import { UiContext, UiProvider } from '@/providers/UiContext/MainUi'
import { CurrentMusicProvider } from '@/providers/currentMusicContext/currentMusic'
import { UrlProvider } from '@/providers/urlVisited/urlVisited'

const figTree = Figtree({
  subsets: ["latin"],
  display: 'swap',
  variable:'--font-roboto',
  weight: ['300','400','500','600','700','800','900'],
})

export const metadata = {
  title: 'Spotify clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
    <html lang="en">
        <body className={figTree.className} >
            <AuthProvider>
              <UrlProvider>
              <CurrentMusicProvider>
            <UiProvider>
            <div className="h-screen">
                <div className="w-full h-full  grid grid-cols-11 grid-rows-1 gap-2 ">
                      <LeftBar />   
                      
                  {children}  
                      <RightBar />
                      <FooterPlayer/>
              </div>
                      
              {/* <div className="h-[13%] flex flex-shrink-0">
                <FooterPlayer />
              </div> */}
              </div>
              </UiProvider>
                </CurrentMusicProvider>
                </UrlProvider>
          </AuthProvider>
      </body> 
    </html>
  )

}
