"use client"
import AuthProvider from '@/providers/AuthProvider'
import './globals.css'
import { usePathname, useRouter } from 'next/navigation'
import { Poppins } from 'next/font/google'
import { LeftBar } from '@/components/leftBar/LeftBar'
import { RightBar } from '@/components/rightBar/RightBar'
import { FooterPlayer } from '@/components/footerPlayer/FooterPlayer'
import { UiContext, UiProvider } from '@/providers/UiContext/MainUi'
import { useContext, useEffect, useState } from 'react'
import { CurrentMusicProvider } from '@/providers/currentMusicContext/currentMusic'
import { UrlProvider } from '@/providers/urlVisited/urlVisited'

const poppins = Poppins({
  subsets: ["latin"],
  display: 'swap',
  variable:'--font-roboto',
  weight: ['300','400','500','600','700','800','900'],
})

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  const path = usePathname()
  const { right,center } = useContext(UiContext)
  console.log(`${center}`);
    return (
    <html lang="en">
        <body className={poppins.className} >
          {path.includes("dashboard") ?
           <AuthProvider>
              {children}
           </AuthProvider>
            :
            <AuthProvider>
              <UrlProvider>
              <CurrentMusicProvider>
            <UiProvider>
            <div className="h-screen flex flex-col">
                <div className="w-screen h-[87%] grid grid-cols-11 grid-rows-1 gap-2 p-2">
                      <LeftBar />    
                  {children}  
                  <RightBar />   
              </div>
              <div className="h-[13%] flex flex-shrink-0">
                <FooterPlayer />
              </div>
              </div>
              </UiProvider>
                </CurrentMusicProvider>
                </UrlProvider>
          </AuthProvider>
          }
      </body> 
    </html>
  )

}
